/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import view.SeatSelection;
/**
 *
 * @author devik
 */
public class BookTicket extends javax.swing.JFrame {
    private int userId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookTicket.class.getName());

    /**
     * Creates new form BookTicket
     */
    

    public BookTicket(int id) {
    initComponents();
    tblBuses.getColumnModel().getColumn(0).setMinWidth(0);
tblBuses.getColumnModel().getColumn(0).setMaxWidth(0);
tblBuses.getColumnModel().getColumn(0).setPreferredWidth(0);
// Repeat for Column index 1 if you want to hide Bus ID too
    this.userId = id; // The ID is now safely stored here!
    setLocationRelativeTo(null);
  
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearchSource = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchDest = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuses = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtBusId = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        txtSearchSource.addActionListener(this::txtSearchSourceActionPerformed);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Source:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Search Destination:");

        btnSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tblBuses.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblBuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ScheduleID", "Bus ID", "Bus No", "Source", "Destination", "Fare", "Travel Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBuses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBusesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuses);
        if (tblBuses.getColumnModel().getColumnCount() > 0) {
            tblBuses.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblBuses.getColumnModel().getColumn(3).setPreferredWidth(120);
            tblBuses.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblBuses.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Bus ID:");

        btnConfirm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnConfirm.setText("Confirm Booking");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Search Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtBusId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSearchSource, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSearchDest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(201, 201, 201))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSearch)
                                .addGap(269, 269, 269))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(btnBack)
                .addGap(75, 75, 75)
                .addComponent(btnConfirm)
                .addGap(0, 164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnBack))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchSourceActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
String source = txtSearchSource.getText().trim();
    String dest = txtSearchDest.getText().trim();
    
    if (jDateChooser1.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Please select a travel date!");
        return; 
    }

    java.text.SimpleDateFormat dFormat = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String travelDate = dFormat.format(jDateChooser1.getDate());

    DefaultTableModel model = (DefaultTableModel) tblBuses.getModel();
    model.setRowCount(0); 

    try {
        java.sql.Connection con = dao.ConnectionProvider.getCon();
        
        // Use JOIN to get bus details and schedule details together
         // This SQL now searches for a 4-day window (Selected Date minus 1, plus 2)
           String query = "SELECT s.schedule_id, s.bus_id, b.bus_number, b.source, b.destination, s.fare, s.travel_date " +
                         "FROM schedules s JOIN buses b ON s.bus_id = b.bus_id " +
                         "WHERE LOWER(b.source) = LOWER(?) " + 
                         "AND LOWER(b.destination) = LOWER(?) " + 
                         "AND s.travel_date BETWEEN DATE_SUB(?, INTERVAL 1 DAY) AND DATE_ADD(?, INTERVAL 2 DAY) " +
                         "ORDER BY s.travel_date ASC";

        java.sql.PreparedStatement ps = con.prepareStatement(query);
        
        // FIX: Remove the "%" symbols. Use exact matches for source and dest.
        ps.setString(1, source);
        ps.setString(2, dest);
        ps.setString(3, travelDate);
        ps.setString(4, travelDate);
        
        java.sql.ResultSet rs = ps.executeQuery();
        
        boolean found = false;
        while(rs.next()) {
            found = true;
            model.addRow(new Object[]{
                rs.getInt("schedule_id"), // Index 0 (Hidden)
                rs.getInt("bus_id"),      // Index 1
                rs.getString("bus_number"),
                rs.getString("source"),
                rs.getString("destination"),
                rs.getDouble("fare"),
                rs.getString("travel_date")
            });
        }
        
        if (!found) {
            JOptionPane.showMessageDialog(null, "No buses found for " + source + " to " + dest + " on " + travelDate);
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Search Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    // If the userId is 1 (Admin), go to Dashboard. 
    // Otherwise, go to UserDashboard.
    if (this.userId == 1) { 
        new Dashboard(this.userId).setVisible(true);
    } else {
        new UserDashboard(this.userId).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    }
    
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
      int row = tblBuses.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Please select a bus from the table!");
        return;
    }

    try {
        // We take the IDs directly from the table (Hidden columns 0 and 1)
        int scheduleId = Integer.parseInt(tblBuses.getValueAt(row, 0).toString());
        int busId = Integer.parseInt(tblBuses.getValueAt(row, 1).toString());
        
        // Get the strings for the next window
        String travelDate = tblBuses.getValueAt(row, 6).toString();
        String route = tblBuses.getValueAt(row, 3).toString() + " - " + tblBuses.getValueAt(row, 4).toString();

        // Pass everything to SeatSelection
        new view.SeatSelection(scheduleId, this.userId, travelDate, busId, route).setVisible(true);
        
        this.dispose();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Selection Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void tblBusesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBusesMouseClicked
        // TODO add your handling code here:
        int index = tblBuses.getSelectedRow();
        TableModel model = tblBuses.getModel();
        // Get the ID from the first column (index 0)
        txtBusId.setText(model.getValueAt(index, 0).toString());
    }//GEN-LAST:event_tblBusesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->{
            new BookTicket(1).setVisible(true);
                });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnSearch;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuses;
    private javax.swing.JTextField txtBusId;
    private javax.swing.JTextField txtSearchDest;
    private javax.swing.JTextField txtSearchSource;
    // End of variables declaration//GEN-END:variables
}
