/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;


/**
 *
 * @author devik
 */

public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    public static int currentUserId;
    private int userId;
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard(int userId) {
       initComponents();
       // Right after initComponents();
 this.setSize(this.getWidth(), this.getHeight() + 40); 
  this.setLocationRelativeTo(null);
// This sets the background of the entire window to a clean, light gray
    this.getContentPane().setBackground(new java.awt.Color(245, 246, 250));
   btnLogout.setForeground(new java.awt.Color(192, 57, 43));
    this.userId = userId;
    setLocationRelativeTo(null);
    
    // Debug line: This will tell you exactly what ID is being received
    System.out.println("Login ID received: " + userId); 

    if (userId == 1) { // Make sure your Admin ID in the DB is actually 1
        jLabel1.setText("ADMIN CONTROL PANEL");
        btnManageBuses.setVisible(true);
        btnManageSchedules.setVisible(true);
    } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageBuses = new javax.swing.JButton();
        btnBookTicket = new javax.swing.JButton();
        btnViewBookings = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnManageSchedules = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ADMIN CONTROL PANEL");
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnManageBuses.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnManageBuses.setText("Manage Buses");
        btnManageBuses.addActionListener(this::btnManageBusesActionPerformed);

        btnBookTicket.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBookTicket.setText("Book Ticket");
        btnBookTicket.addActionListener(this::btnBookTicketActionPerformed);

        btnViewBookings.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnViewBookings.setText("View Bookings");
        btnViewBookings.addActionListener(this::btnViewBookingsActionPerformed);

        btnLogout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnManageSchedules.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnManageSchedules.setText("Manage Schedules");
        btnManageSchedules.addActionListener(this::btnManageSchedulesActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageBuses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageSchedules, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(btnBookTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewBookings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnManageBuses, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageSchedules, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBookTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewBookings, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true); // Go back to login
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookingsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ViewBookings(this.userId).setVisible(true);
    }//GEN-LAST:event_btnViewBookingsActionPerformed

    private void btnBookTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookTicketActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        new BookTicket(this.userId).setVisible(true);
    }//GEN-LAST:event_btnBookTicketActionPerformed

    private void btnManageBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBusesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new ManageBus().setVisible(true);
    }//GEN-LAST:event_btnManageBusesActionPerformed

    private void btnManageSchedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSchedulesActionPerformed
        // TODO add your handling code here:
        this.dispose();
    new ManageSchedules().setVisible(true);
    }//GEN-LAST:event_btnManageSchedulesActionPerformed

    private void jLabel1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
       java.awt.EventQueue.invokeLater(() -> {
    new Dashboard(1).setVisible(true);
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBookTicket;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageBuses;
    private javax.swing.JButton btnManageSchedules;
    private javax.swing.JButton btnViewBookings;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
