/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.ConnectionProvider;
import java.sql.*;
import javax.swing.JOptionPane;

import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
/**
 *
 * @author devik
 */
public class Login extends javax.swing.JFrame {  
   
    public static int currentUserId;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // Professional Palette
        // Add this inside the public Login() constructor
        this.setSize(600, 450);
        this.setResizable(false);
       this.getRootPane().setDefaultButton(btnLogin);
        this.getContentPane().setBackground(new java.awt.Color(245, 246, 250));
        
// Apply to the content pane
            setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();

        jButton1.setText("Create New Account");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("     SMART BUS LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        txtUsername.addActionListener(this::txtUsernameActionPerformed);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 71, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 71, -1));

        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setDefaultCapable(false);
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 85, -1));

        btnExit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 86, -1));

        btnSignup.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnSignup.setText("Create New Account");
        btnSignup.setDefaultCapable(false);
        btnSignup.setFocusCycleRoot(true);
        btnSignup.addActionListener(this::btnSignupActionPerformed);
        getContentPane().add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
         // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
    String password = new String(txtPassword.getPassword());
    if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter both Username and Password.");
            return;
        }
    try {
        java.sql.Connection con = dao.ConnectionProvider.getCon();
    
    // 1. Use '?' instead of putting variables directly in the string (Secures your app!)
    String query = "SELECT id, role FROM users WHERE username=? AND password=?";
    java.sql.PreparedStatement ps = con.prepareStatement(query);
    ps.setString(1, username);
    ps.setString(2, password);

    java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            
            int idFromDB = rs.getInt("id"); 
        String role = rs.getString("role");
        
        // Save the ID so other windows can see who is logged in
        currentUserId = idFromDB;
           // 3. Logic for switching between Admin and User
        if (role != null && role.equalsIgnoreCase("admin")) {
               JOptionPane.showMessageDialog(null, "Admin Access Granted!");
        
        // FIX: Pass the 'idFromDB' into the Dashboard constructor!
        new Dashboard(idFromDB).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Login Successful! Welcome to SmartBus.");
        
        // If you have a separate UserDashboard, keep this:
        new UserDashboard(idFromDB).setVisible(true);
        }
        
        // 4. Close the login window
        this.dispose(); 
        
    }else {
            javax.swing.JOptionPane.showMessageDialog(null, "Invalid Username or Password!");
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Kill the Login window so it doesn't stay open in the background
    new Signup().setVisible(true); // Open our new Signup screen
    }//GEN-LAST:event_btnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    // 1. Set the Look and Feel (The Uniform)
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    
    java.awt.EventQueue.invokeLater(() -> {
        new Login().setVisible(true);
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
