/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Calendar;
/**
 *
 * @author devik
 */
public class ManageSchedules extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageSchedules.class.getName());

    /**
     * Creates new form ManageSchedules
     */
    public ManageSchedules() {
        initComponents();
       this.setPreferredSize(new java.awt.Dimension(700, 550));
        this.pack();
        setLocationRelativeTo(null); 
        loadBusesToCombo();
        loadScheduleTable();
         this.getContentPane().setBackground(new java.awt.Color(245, 246, 250));
    }
private void loadBusesToCombo() {
        try {
            Connection con = dao.ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT bus_id, bus_number FROM buses");
            comboBuses.removeAllItems(); 
            while(rs.next()) {
                comboBuses.addItem(rs.getString("bus_id") + " - " + rs.getString("bus_number"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
        }
    }
    
    private void loadScheduleTable() {
        DefaultTableModel model = (DefaultTableModel) tblSchedules.getModel();
    model.setRowCount(0); 
    // Match the columns used in your loadData/Delete logic
    model.setColumnIdentifiers(new String[]{"ID", "Bus No", "Date", "Fare", "Seats"});
    try {
        Connection con = dao.ConnectionProvider.getCon();
        String query = "SELECT s.schedule_id, b.bus_number, s.travel_date, s.fare, s.available_seats " +
                       "FROM schedules s JOIN buses b ON s.bus_id = b.bus_id";
        ResultSet rs = con.createStatement().executeQuery(query);
        while(rs.next()) {
            model.addRow(new Object[]{
                rs.getString("schedule_id"), 
                rs.getString("bus_number"), 
                rs.getString("travel_date"), 
                rs.getString("fare"),
                rs.getString("available_seats")
            });
        }
    } catch (Exception e) {
        System.out.println("Table Load Error: " + e.getMessage());
    }
    }
/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBuses = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtFare = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDeleteSelected = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedules = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Select Bus");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        comboBuses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBuses.addActionListener(this::comboBusesActionPerformed);
        getContentPane().add(comboBuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));
        getContentPane().add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Fare");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        txtFare.addActionListener(this::txtFareActionPerformed);
        getContentPane().add(txtFare, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 71, -1));

        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAdd.setText("Add to Schedule");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        btnDeleteSelected.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDeleteSelected.setText("Delete Selected");
        btnDeleteSelected.addActionListener(this::btnDeleteSelectedActionPerformed);
        getContentPane().add(btnDeleteSelected, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        tblSchedules.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblSchedules.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Bus No", "Date", "Fare"
            }
        ));
        jScrollPane1.setViewportView(tblSchedules);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 440, 200));

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFareActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try {
            String busId = comboBuses.getSelectedItem().toString().split(" - ")[0];
            String date = new SimpleDateFormat("yyyy-MM-dd").format(dateChooser.getDate());
            double fare = Double.parseDouble(txtFare.getText());
            
            Connection con = dao.ConnectionProvider.getCon();
            PreparedStatement ps = con.prepareStatement("INSERT INTO schedules (bus_id, travel_date, available_seats, fare) VALUES (?, ?, 40, ?)");
            ps.setString(1, busId);
            ps.setString(2, date);
            ps.setDouble(3, fare);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successfully Added!");
            loadScheduleTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new Dashboard(1).setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSelectedActionPerformed
        // TODO add your handling code here:
        // 1. Get the selected row index
    int selectedRow = tblSchedules.getSelectedRow(); 
    
    // 2. Check if a row is actually selected
    if(selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a schedule from the table first!");
        return;
    }

    // 3. Get the ID from the first column (Index 0)
    // Make sure your table's first column is the Schedule ID
    String scheduleId = tblSchedules.getValueAt(selectedRow, 0).toString();
    
    // 4. Confirmation Popup
    int confirm = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to delete Schedule ID: " + scheduleId + "?", 
        "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        
    if(confirm == JOptionPane.YES_OPTION) {
        try {
            java.sql.Connection con = dao.ConnectionProvider.getCon();
            // Using a Prepared Statement to prevent SQL injection
            java.sql.PreparedStatement ps = con.prepareStatement("DELETE FROM schedules WHERE schedule_id = ?");
            ps.setString(1, scheduleId);
            
            int result = ps.executeUpdate();
            
            if(result > 0) {
                JOptionPane.showMessageDialog(this, "Schedule deleted successfully!");
                loadData(); // This refreshes your table so the deleted row disappears
            } else {
                JOptionPane.showMessageDialog(this, "Error: Schedule ID not found in database.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnDeleteSelectedActionPerformed

    private void comboBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBusesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBusesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageSchedules().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteSelected;
    private javax.swing.JComboBox<String> comboBuses;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSchedules;
    private javax.swing.JTextField txtFare;
    // End of variables declaration//GEN-END:variables

private void loadData() {
    
    DefaultTableModel model = (DefaultTableModel) tblSchedules.getModel();
    // Make sure this line is at the top of loadData()
    model.setColumnIdentifiers(new Object[]{"ID", "Bus ID", "Travel Date", "Seats", "Fare"});
    model.setRowCount(0); // Clear the table first

    try {
        java.sql.Connection con = dao.ConnectionProvider.getCon();
        java.sql.Statement st = con.createStatement();
        // Make sure your table name in MySQL is 'schedules'
        java.sql.ResultSet rs = st.executeQuery("SELECT * FROM schedules");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("schedule_id"),
                rs.getString("bus_id"),
                rs.getString("travel_date"),
                rs.getString("available_seats"),
                rs.getString("fare")
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error loading schedules: " + e.getMessage());
    }
}
}
