/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author devik
 */
public class ManageBus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageBus.class.getName());

    /**
     * Creates new form ManageBus
     */
   public ManageBus() {
    initComponents();
    buttonGroup1.add(rbAC);
    buttonGroup1.add(rbNonAC);
    jDateChooser1.setMinSelectableDate(new java.util.Date());
    // Group the radio buttons so only one can be selected
    javax.swing.ButtonGroup busTypeGroup = new javax.swing.ButtonGroup();
    busTypeGroup.add(rbAC);
    busTypeGroup.add(rbNonAC);
    tblBuses.setRowHeight(30);
     this.getContentPane().setBackground(new java.awt.Color(245, 246, 250));
    tblBuses.getColumnModel().getColumn(0).setMinWidth(0);
    tblBuses.getColumnModel().getColumn(0).setMaxWidth(0);
    tblBuses.getColumnModel().getColumn(1).setPreferredWidth(100); // Bus No
    tblBuses.getColumnModel().getColumn(4).setPreferredWidth(50);  // Fare
    // Optional: Set a default selection
    rbAC.setSelected(true); 
    // 1. Set the size to be wide enough for the table but not 'stretched'
        this.setSize(800, 600); 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    this.setSize(850, 750);
    this.setLocationRelativeTo(null);
    loadAllBuses();
    this.getContentPane().setBackground(new java.awt.Color(235, 235, 240));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBuses = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBusNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFare = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        rbAC = new javax.swing.JRadioButton();
        rbNonAC = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 250));

        tblBuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Bus No.", "Source", "Dest", "Fare", "Type", "Travel Date"
            }
        ));
        tblBuses.setPreferredSize(new java.awt.Dimension(1050, 250));
        jScrollPane2.setViewportView(tblBuses);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 670, 250));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Manage Buses");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 190, 40));

        jLabel2.setText("Bus Number:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 20));
        getContentPane().add(txtBusNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 160, -1));

        jLabel3.setText("Source:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        txtSource.addActionListener(this::txtSourceActionPerformed);
        getContentPane().add(txtSource, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 160, -1));

        jLabel4.setText("Destination:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        txtDestination.addActionListener(this::txtDestinationActionPerformed);
        getContentPane().add(txtDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 160, -1));

        jLabel5.setText("Fare:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        txtFare.addActionListener(this::txtFareActionPerformed);
        getContentPane().add(txtFare, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 160, -1));

        btnSave.setText("Save Bus");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, -1, -1));

        jLabel8.setText("Type:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 50, -1));

        rbAC.setText("AC");
        rbAC.addActionListener(this::rbACActionPerformed);
        getContentPane().add(rbAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        rbNonAC.setText("NonAC");
        rbNonAC.addActionListener(this::rbNonACActionPerformed);
        getContentPane().add(rbNonAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jLabel6.setText("Travel Date(YYYY-MM-DD):");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String busNum = txtBusNumber.getText().trim();
    String source = txtSource.getText().trim();
    String destination = txtDestination.getText().trim();
    String fare = txtFare.getText().trim();
    if (!busNum.matches("^[A-Z]{2}-\\d{2}-[A-Z]{2}-\\d{4}$")) {
    JOptionPane.showMessageDialog(null, "Please use format: AP-31-TV-1234");
    return;
    }
    String tDate = "";
    if (jDateChooser1.getDate() != null) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        tDate = sdf.format(jDateChooser1.getDate());
    }
    // ---------------------------------

    String type = "";
    if(rbAC.isSelected()) type = "AC";
    else if(rbNonAC.isSelected()) type = "Non-AC";

    if(busNum.isEmpty() || source.isEmpty() || destination.isEmpty() || fare.isEmpty() || tDate.isEmpty() || type.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill all fields and select a Bus Type!");
        return;
    }
    // Logic to ensure a type is picked
    
    try {
        java.sql.Connection con = dao.ConnectionProvider.getCon();
        String query = "INSERT INTO buses (bus_number, source, destination, fare, bus_type, travel_date) VALUES (?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement ps = con.prepareStatement(query);
        
        ps.setString(1, busNum);
        ps.setString(2, source);
        ps.setString(3, destination);
        ps.setDouble(4, Double.parseDouble(fare)); 
        ps.setString(5, type);
        ps.setString(6, tDate);
        
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Bus " + busNum + " added successfully for " + tDate);
        
        loadAllBuses();
        
        // Clear fields after success
        txtBusNumber.setText("");
        txtSource.setText("");
        txtDestination.setText("");
        txtFare.setText("");
        jDateChooser1.setDate(null);
        rbAC.setSelected(true);
        txtSource.setText("");
        txtDestination.setText("");
        // busTypeGroup.clearSelection(); // Optional
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Fare must be a valid number!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose(); // This hides the ManageBus screen
        new Dashboard(1).setVisible(true); // This opens your Dashboard again
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSourceActionPerformed

    private void txtFareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFareActionPerformed

    private void rbACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbACActionPerformed

    private void txtDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinationActionPerformed

    private void rbNonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNonACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNonACActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageBus().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbAC;
    private javax.swing.JRadioButton rbNonAC;
    private javax.swing.JTable tblBuses;
    private javax.swing.JTextField txtBusNumber;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFare;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables

public void loadAllBuses() {
    DefaultTableModel model = (DefaultTableModel) tblBuses.getModel();
    model.setRowCount(0);
    try {
        Connection con = dao.ConnectionProvider.getCon();
        PreparedStatement ps = con.prepareStatement(
            "SELECT bus_id, bus_number, source, destination, fare, bus_type, travel_date FROM buses"
        );
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("bus_id"),
                rs.getString("bus_number"),
                rs.getString("source"),
                rs.getString("destination"),
                rs.getDouble("fare"),
                rs.getString("bus_type"),
                rs.getString("travel_date")
            });
        }
        // Force the table to visually refresh
        tblBuses.revalidate();
        tblBuses.repaint();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Load Error: " + e.getMessage());
    }
}
}
