/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.EventQueue;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author devik
 */
public class ViewBookings extends javax.swing.JFrame {
    private int userId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewBookings.class.getName());

    /**
     * Creates new form ViewBookings
     */
    public ViewBookings(int userId) {
        initComponents();
        this.userId = userId;
        setLocationRelativeTo(null);
        loadData();
        tblAllBookings.getColumnModel().getColumn(0).setMinWidth(0);
        tblAllBookings.getColumnModel().getColumn(0).setMaxWidth(0);
        tblAllBookings.getColumnModel().getColumn(0).setWidth(0);
            this.getContentPane().setBackground(new java.awt.Color(245, 246, 250));

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllBookings = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblTotalRevenue = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnViewTicket = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAllBookings.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblAllBookings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Passenger", "BusNo.", "route", "date", "Amount"
            }
        ));
        tblAllBookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAllBookingsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAllBookings);
        if (tblAllBookings.getColumnModel().getColumnCount() > 0) {
            tblAllBookings.getColumnModel().getColumn(0).setPreferredWidth(60);
            tblAllBookings.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblAllBookings.getColumnModel().getColumn(2).setPreferredWidth(60);
            tblAllBookings.getColumnModel().getColumn(3).setPreferredWidth(210);
            tblAllBookings.getColumnModel().getColumn(4).setPreferredWidth(120);
            tblAllBookings.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        btnBack.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("BOOKINGS");

        btnDelete.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDelete.setText("Delete Booking");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        lblTotalRevenue.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTotalRevenue.setText("Total Revenue: ");

        txtSearch.addActionListener(this::txtSearchActionPerformed);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Search Passenger:");

        btnViewTicket.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnViewTicket.setText("View Ticket");
        btnViewTicket.addActionListener(this::btnViewTicketActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnBack)
                                .addGap(47, 47, 47)
                                .addComponent(btnDelete)
                                .addGap(52, 52, 52)
                                .addComponent(btnViewTicket)))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTotalRevenue)
                        .addGap(88, 88, 88))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnDelete)
                    .addComponent(btnViewTicket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalRevenue)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
        new Dashboard(this.userId).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int row = tblAllBookings.getSelectedRow(); // Make sure this matches your table name
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a booking to cancel!");
        return;
    }

    try {
        // 1. Get the Date (Check if it is index 6!)
        String dateStr = tblAllBookings.getValueAt(row, 4).toString().trim();
        java.time.LocalDate travelDate = java.time.LocalDate.parse(dateStr);
        java.time.LocalDate today = java.time.LocalDate.now();

        // DEBUG POPUP: This will tell us if the dates are being read correctly
        // System.out.println("Comparing " + travelDate + " with " + today);

        // 2. THE BLOCKER
        if (travelDate.isBefore(today)) {
            JOptionPane.showMessageDialog(this, 
                "You cannot cancel a past booking.\nTrip Date: " + dateStr + "\nToday: " + today, 
                "Cancellation Denied", 
                JOptionPane.ERROR_MESSAGE);
            return; 
        }

        // 3. Normal logic only runs if date is Today or Future
        int confirm = JOptionPane.showConfirmDialog(this, "Cancel this ticket?", "Confirm", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            String bookingId = tblAllBookings.getValueAt(row, 0).toString();
            java.sql.Connection con = dao.ConnectionProvider.getCon();
            java.sql.PreparedStatement ps = con.prepareStatement("DELETE FROM bookings WHERE booking_id = ?");
            ps.setString(1, bookingId);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Cancelled! Your seat is now available for others.");
            loadData();
            // refresh your table here, e.g., loadData();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String searchName = txtSearch.getText();
        searchData(searchName);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnViewTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTicketActionPerformed
        int row = tblAllBookings.getSelectedRow();
    
    if(row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a booking from the table first!");
        return;
    }

    try {
        // SAFETY MATH: Check if the value is null before calling .toString()
        Object idVal = tblAllBookings.getValueAt(row, 0);
        Object passVal = tblAllBookings.getValueAt(row, 1);
        Object busVal = tblAllBookings.getValueAt(row, 2);
        Object routeVal = tblAllBookings.getValueAt(row, 3);
        Object dateVal = tblAllBookings.getValueAt(row, 4);
        Object amtVal = tblAllBookings.getValueAt(row, 5);

        // Convert to String safely
        String id = (idVal != null) ? idVal.toString() : "N/A";
        String passenger = (passVal != null) ? passVal.toString() : "N/A";
        String busNo = (busVal != null) ? busVal.toString() : "N/A";
        String route = (routeVal != null) ? routeVal.toString() : "N/A";
        String travelDate = (dateVal != null) ? dateVal.toString() : "N/A";
        String amount = (amtVal != null) ? amtVal.toString() : "0";

        // Format the Ticket
        String ticket = "------------------------------------------------------------\n"
                      + "             🚌 E-TICKET RECEIPT             \n"
                      + "------------------------------------------------------------\n"
                      + " Booking ID:      #" + id + "\n"
                      + " Passenger Name:  " + passenger + "\n"
                      + " Travel Date:     " + travelDate + "\n"
                      + "------------------------------------------------------------\n"
                      + " Bus Number:      " + busNo + "\n"
                      + " Bus Route:       " + route + "\n"
                      + "------------------------------------------------------------\n"
                      + " TOTAL PAID:      ₹" + amount + "\n"
                      + "------------------------------------------------------------\n"
                      + "        Thank you for traveling with us!            \n"
                      + "------------------------------------------------------------";

        // SHOW THE POPUP
        JOptionPane.showMessageDialog(this, ticket, "Ticket Details", JOptionPane.INFORMATION_MESSAGE);

        // Print choice
        int choice = JOptionPane.showConfirmDialog(this, "Do you want to save this as a .txt file?", "Print", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            saveTicketToFile(passenger, ticket);
        }

    } catch (Exception e) {
        // This will now tell you exactly what went wrong instead of staying silent
        JOptionPane.showMessageDialog(this, "Error building ticket: " + e.getMessage());
    }
    

    }//GEN-LAST:event_btnViewTicketActionPerformed

    private void saveTicketToFile(String passenger, String ticketContent) {
    try {
        // STEP 1: Tell Java to find your Desktop automatically
        String userHome = System.getProperty("user.home");
        
        // STEP 2: Create the full path to the Desktop
        String fileName = userHome + "/Desktop/" + passenger.replaceAll("\\s+", "_") + "_Ticket.txt"; 
        
        // STEP 3: Write the file
        java.io.FileWriter writer = new java.io.FileWriter(fileName);
        writer.write(ticketContent);
        writer.close();
        
        // STEP 4: Success Message
        JOptionPane.showMessageDialog(this, "Ticket saved to your DESKTOP as: " + fileName);
        
    } catch (java.io.IOException e) {
        JOptionPane.showMessageDialog(this, "Print Error: " + e.getMessage());
    }
}

    private void tblAllBookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllBookingsMouseClicked
        // TODO add your handling code here:
        try {
        int row = tblAllBookings.getSelectedRow();
        if (row != -1) {
            // 1. Get the date string from Column 6
                String dateStr = tblAllBookings.getValueAt(row, 4).toString().trim();
            // 2. Convert to LocalDate
            java.time.LocalDate travelDate = java.time.LocalDate.parse(dateStr);
            java.time.LocalDate today = java.time.LocalDate.now();

            // 3. Gray out button if the date is in the past
            if (travelDate.isBefore(today)) {
                btnDelete.setEnabled(false); // Make button unclickable
                btnDelete.setToolTipText("Cannot delete past bookings"); 
            } else {
                btnDelete.setEnabled(true);  // Make button clickable
                btnDelete.setToolTipText(null);
            }
        }
    } catch (Exception e) {
        // This avoids the app crashing if a date is formatted weirdly
        btnDelete.setEnabled(true); 
    }
    }//GEN-LAST:event_tblAllBookingsMouseClicked

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        // Pass 1 as a default for testing the Admin view
        new ViewBookings(1).setVisible(true); 
    });
    }
    
    // ... other code ...

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnViewTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JTable tblAllBookings;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

private void loadData() {
  DefaultTableModel model = (DefaultTableModel) tblAllBookings.getModel();
    model.setColumnIdentifiers(new Object[]{"ID", "Passenger","Bus No", "Route","Date", "Amount"});
    model.setRowCount(0); 

    try {
        java.sql.Connection con = dao.ConnectionProvider.getCon();
        String query;
        
        // 1. Build the Query
        if (this.userId == 1) { 
            // ADMIN QUERY (No WHERE clause, so NO "?" exists)
            query = "SELECT b.booking_id, b.passenger_name, bus.bus_number, " +
                    "CONCAT(bus.source, ' - ', bus.destination), b.travel_date, b.total_amount " +
                    "FROM bookings b INNER JOIN buses bus ON b.bus_id = bus.bus_id";
        } else {
            // USER QUERY (Has one WHERE clause, so ONE "?" exists)
            query = "SELECT b.booking_id, b.passenger_name, bus.bus_number, " +
                    "CONCAT(bus.source, ' - ', bus.destination), b.travel_date, b.total_amount " +
                    "FROM bookings b INNER JOIN buses bus ON b.bus_id = bus.bus_id " +
                    "WHERE b.user_id = ?";
        }

        java.sql.PreparedStatement ps = con.prepareStatement(query);
        
        // 2. Set the parameter ONLY if we are NOT the admin
        if (this.userId != 1) {
            ps.setInt(1, this.userId); 
        }
        
        // 3. Execute
        java.sql.ResultSet rs = ps.executeQuery();
        
        while(rs.next()) {
            model.addRow(new Object[]{
                rs.getString(1), rs.getString(2), rs.getString(3), 
                rs.getString(4), rs.getString(5), rs.getString(6) 
            });
        }
        
        calculateRevenue();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error in LoadData: " + e.getMessage());
    }

}

private void searchData(String name) {
    DefaultTableModel model = (DefaultTableModel) tblAllBookings.getModel();
    model.setRowCount(0);
    try {
        java.sql.Connection con = dao.ConnectionProvider.getCon();
        String query = "SELECT b.booking_id, b.passenger_name, bus.bus_number, " +
                       "CONCAT(bus.source, ' - ', bus.destination), b.travel_date, b.total_amount " +
                       "FROM bookings b INNER JOIN buses bus ON b.bus_id = bus.bus_id " +
                       "WHERE b.passenger_name LIKE ?";

        java.sql.PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, "%" + name + "%");

        java.sql.ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6)
            });
        }
        calculateRevenue();
    } catch (Exception e) {
        System.out.println("Search Error: " + e.getMessage());
    }
}

private void calculateRevenue() {
    double total = 0; // Reset to zero every time!
    DefaultTableModel model = (DefaultTableModel) tblAllBookings.getModel();
    
    if (model.getRowCount() == 0) {
        lblTotalRevenue.setText("Total Revenue: ₹0.00");
        return;
    }
    
    for (int i = 0; i < model.getRowCount(); i++) {
        try {
            // We use index 5 because "Amount" is the 6th column
            Object value = model.getValueAt(i, 5);
            if (value != null) {
                String amtStr = value.toString();
                String cleanAmt = amtStr.replaceAll("[^0-9.]", "");
                
                if (!cleanAmt.isEmpty()) {
                    total += Double.parseDouble(cleanAmt);
            }
          }
        } catch (Exception e) {
            System.out.println("Row " + i + " skipped: " + e.getMessage());
        }
        }
    lblTotalRevenue.setText("Total Revenue: ₹" + String.format("%.2f", total));
}

}
