package view;

import java.sql.*;
import dao.ConnectionProvider;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.time.LocalDate;

public class ViewMyHistory extends javax.swing.JFrame {
    
   private int userId;

    public ViewMyHistory() {
        initComponents();
        hideColumns();
    }
    
    // Logic Constructor (The one our UserDashboard uses)
    public ViewMyHistory(int id) {

        this.userId = id;
        initComponents();
        hideColumns();
        setLocationRelativeTo(null);
        loadMyBookings();
             this.getContentPane().setBackground(new java.awt.Color(245, 246, 250));

    }
    private void hideColumns() {
       tblMyHistory.getColumnModel().getColumn(0).setMinWidth(0);
        tblMyHistory.getColumnModel().getColumn(0).setMaxWidth(0);
        tblMyHistory.getColumnModel().getColumn(1).setMinWidth(0);
        tblMyHistory.getColumnModel().getColumn(1).setMaxWidth(0);
    }

    private void loadMyBookings() {
        DefaultTableModel model = (DefaultTableModel) tblMyHistory.getModel();
        model.setColumnIdentifiers(new Object[]{"BID", "SID", "Route", "Passenger", "seats", "Total Paid", "Travel Date"});
        model.setRowCount(0);
        try {
            Connection con = ConnectionProvider.getCon();
            String query = "SELECT booking_id, schedule_id, route, passenger_name, seats_booked, total_amount, travel_date "
                         + "FROM bookings WHERE user_id = ?";

            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, this.userId);
            ResultSet rs = ps.executeQuery();
       
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt(1),    // BID
                    rs.getInt(2),    // SID
                    rs.getString(3), // Route
                    rs.getString(4), // Passenger
                    rs.getInt(5),    // Seats
                    rs.getDouble(6), // Total Paid
                    rs.getString(7)  // Travel Date
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
          
    // ... Keep your initComponents() and variables exactly as they are below ...
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyHistory = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewMyTicket = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMyHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "BID", "SID", "Route", "Passenger", "seats", "Total Paid", "Travel Date"
            }
        ));
        jScrollPane1.setViewportView(tblMyHistory);
        if (tblMyHistory.getColumnModel().getColumnCount() > 0) {
            tblMyHistory.getColumnModel().getColumn(0).setPreferredWidth(80);
            tblMyHistory.getColumnModel().getColumn(2).setPreferredWidth(150);
            tblMyHistory.getColumnModel().getColumn(3).setPreferredWidth(150);
            tblMyHistory.getColumnModel().getColumn(4).setPreferredWidth(60);
            tblMyHistory.getColumnModel().getColumn(5).setPreferredWidth(130);
            tblMyHistory.getColumnModel().getColumn(6).setPreferredWidth(130);
        }

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnViewMyTicket.setText("View My Ticket");
        btnViewMyTicket.addActionListener(this::btnViewMyTicketActionPerformed);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnBack)
                        .addGap(41, 41, 41)
                        .addComponent(btnViewMyTicket)
                        .addGap(44, 44, 44)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnViewMyTicket)
                    .addComponent(btnCancel))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       this.dispose();
        new UserDashboard(this.userId).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewMyTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMyTicketActionPerformed
        // TODO add your handling code here:
     try {
            int selectedRow = tblMyHistory.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Please select a booking to view your ticket!");
                return;
                }

            String id = tblMyHistory.getValueAt(selectedRow, 0).toString();
            String route = tblMyHistory.getValueAt(selectedRow, 2).toString();
            String passenger = tblMyHistory.getValueAt(selectedRow, 3).toString();
            String seats = tblMyHistory.getValueAt(selectedRow, 4).toString();
            String amount = tblMyHistory.getValueAt(selectedRow, 5).toString();
            String travelDate = tblMyHistory.getValueAt(selectedRow, 6).toString();
            
            String ticket = "------------------------------------------------------------\n"
                      + "            🎫  SMARTBUS E-TICKET             \n"
                      + "------------------------------------------------------------\n"
                      + " Booking Ref:  #" + id + "        Date: " + travelDate + "\n"
                      + " Route:        " + route + "\n"
                      + " Passenger:    " + passenger + "\n"
                      + " Seat(s):      " + seats + "\n"
                      + "------------------------------------------------------------\n"
                      + " FARE PAID:    ₹" + amount + "\n"
                      + "------------------------------------------------------------";

            JOptionPane.showMessageDialog(null, ticket, "Your Ticket", JOptionPane.PLAIN_MESSAGE);
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error reading table data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnViewMyTicketActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    int row = tblMyHistory.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a booking to cancel!");
            return;
        }

        try {
            String dateStr = tblMyHistory.getValueAt(row, 6).toString().trim();
            LocalDate travelDate = LocalDate.parse(dateStr);
            LocalDate today = LocalDate.now();

            if (travelDate.isBefore(today)) {
                JOptionPane.showMessageDialog(this, "You cannot cancel a past trip!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                String bId = tblMyHistory.getValueAt(row, 0).toString();
                String sId = tblMyHistory.getValueAt(row, 1).toString();
                // Get seat count for math logic
                int seatsToReturn = Integer.parseInt(tblMyHistory.getValueAt(row, 4).toString());

                Connection con = ConnectionProvider.getCon();
                con.setAutoCommit(false);

                PreparedStatement ps1 = con.prepareStatement("DELETE FROM bookings WHERE booking_id = ?");
                ps1.setString(1, bId);
                ps1.executeUpdate();

                // Logic: Add the correct number of seats back to the schedule
                PreparedStatement ps2 = con.prepareStatement("UPDATE schedules SET available_seats = available_seats + ? WHERE schedule_id = ?");
                ps2.setInt(1, seatsToReturn);
                ps2.setString(2, sId);
                ps2.executeUpdate();

                con.commit();
                JOptionPane.showMessageDialog(this, "Cancelled! Your seats are now available.");
                loadMyBookings();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCancelActionPerformed


    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
   try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new ViewMyHistory(1).setVisible(true);
        }
    });
}
        /* Set the Nimbus look and feel */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnViewMyTicket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMyHistory;
    // End of variables declaration//GEN-END:variables
}